# Generated by Django 5.1.5 on 2025-02-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_audiotranscription_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotranscription',
            name='speaker_type',
            field=models.CharField(blank=True, choices=[('atco', 'ATCO'), ('pilot', 'Pilot'), ('', 'Unspecified')], default='', max_length=10),
        ),
    ]
