# Generated by Django 5.1.5 on 2025-02-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_audiotranscription_speaker_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptiongroup',
            name='validation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcriptiongroup',
            name='validation_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcriptiongroup',
            name='validation_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcriptiongroup',
            name='validation_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
