# Generated by Django 5.1.5 on 2025-05-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_alter_transcriptiongroup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptiongroup',
            name='validation_calification',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcriptiongroup',
            name='validation_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
