# Generated by Django 5.1.5 on 2025-05-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_transcriptiongroup_validation_calification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotranscription',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
