# Generated by Django 5.1.5 on 2025-05-22 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0011_audiotranscription_manual_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiotranscription",
            name="file_hash",
        ),
        migrations.RemoveField(
            model_name="audiotranscription",
            name="modified_text",
        ),
        migrations.RemoveField(
            model_name="audiotranscription",
            name="original_text",
        ),
        migrations.AddField(
            model_name="speechsegment",
            name="modified_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="speechsegment",
            name="segment_file",
            field=models.FileField(blank=True, null=True, upload_to="segments/"),
        ),
        migrations.AlterField(
            model_name="speechsegment",
            name="audio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="segments",
                to="models.audiotranscription",
            ),
        ),
    ]
