# Generated by Django 5.1.5 on 2025-12-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0015_airline_transcriptioncorrection"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TranscriptionCorrection",
        ),
    ]
