# Generated by Django 5.1.5 on 2025-02-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_transcriptiongroup_validation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcriptiongroup',
            name='validation_score',
        ),
    ]
