# Generated by Django 5.1.5 on 2025-03-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_remove_transcriptiongroup_validation_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptiongroup',
            name='validation_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
