# Generated by Django 5.1.5 on 2025-05-22 10:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_audiotranscription_file_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiotranscription',
            name='speaker_type',
        ),
        migrations.CreateModel(
            name='SpeechSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speaker_type', models.CharField(blank=True, choices=[('atco', 'ATCO'), ('pilot', 'Pilot'), ('', 'Unspecified')], default='', max_length=10)),
                ('text', models.TextField(blank=True, null=True)),
                ('start_time', models.FloatField(blank=True, null=True)),
                ('end_time', models.FloatField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='models.audiotranscription')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
