# Generated by Django 5.1.5 on 2025-05-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_remove_audiotranscription_speaker_type_speechsegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotranscription',
            name='manual_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
