# Generated by Django 5.1.5 on 2025-06-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0012_remove_audiotranscription_file_hash_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audiotranscription",
            old_name="manual_order",
            new_name="order",
        ),
        migrations.AlterField(
            model_name="speechsegment",
            name="speaker_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("atco", "ATCO"),
                    ("pilot", "Pilot"),
                    ("", "Unspecified"),
                    ("other", "Other"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
