# Generated by Django 5.1.5 on 2025-06-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0013_rename_manual_order_audiotranscription_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="audiotranscription",
            options={"ordering": ["order"]},
        ),
    ]
