# Generated by Django 5.1.5 on 2025-12-09 15:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Airline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("icao_code", models.CharField(blank=True, max_length=3, null=True)),
                ("iata_code", models.CharField(blank=True, max_length=2, null=True)),
                ("callsign", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AudioTranscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("file", models.FileField(upload_to="audios/")),
                ("file_name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_process", "In Process"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("transcription_date", models.DateTimeField(blank=True, null=True)),
                ("task_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TranscriptionCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incorrect_text",
                    models.CharField(
                        help_text="Texto incorrecto (en minúsculas)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "correct_text",
                    models.CharField(help_text="Texto corregido", max_length=100),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("airline", "Aerolínea"),
                            ("number", "Número"),
                            ("terminology", "Terminología Aeronáutica"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpeechSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "segment_file",
                    models.FileField(blank=True, null=True, upload_to="segments/"),
                ),
                (
                    "speaker_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("atco", "ATCO"),
                            ("pilot", "Pilot"),
                            ("", "Unspecified"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
                ("modified_text", models.TextField(blank=True, null=True)),
                ("start_time", models.FloatField(blank=True, null=True)),
                ("end_time", models.FloatField(blank=True, null=True)),
                ("order", models.PositiveIntegerField()),
                (
                    "audio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="api.audiotranscription",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TranscriptionGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("group_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_process", "In Process"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("completion_date", models.DateTimeField(blank=True, null=True)),
                ("validation_date", models.DateTimeField(blank=True, null=True)),
                (
                    "validation_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("validation_result", models.JSONField(blank=True, null=True)),
                ("validation_score", models.FloatField(blank=True, null=True)),
                ("validation_calification", models.FloatField(blank=True, null=True)),
                ("validation_comment", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="audiotranscription",
            name="transcription_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audios",
                to="api.transcriptiongroup",
            ),
        ),
    ]
